theme = "nord-dark"
icons = "awesome5"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{average}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength} {ip}"
interval = 5

[[block]]
block = "battery"
interval = 10
format = " {percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %r"
