theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "net"
device = "enp2s0"
format = "{speed_down}/{speed_up}"
interval = 5

[[block]]
block = "battery"
interval = 10
format = " {percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d %r"
